### ISSUE TITLE
Editing config.js doesn't change anything

### ISSUE THREAD

**Issue by bonelifer** [michaelx/Launchbot#11]
I've run the npm install command. I've edited the config.js file and ran the npm run build command. But it doesn't reflect in what is shown from the dist folder.

**Comment by michaelx** [comment]
This happens if you are opening Launchbot before changing the embedded `config.js`, it will then store the current config in `localStorage` and use it going forward. To restore your embedded config just click on `Settings > Restore embedded config` (which you’ll find almost at the bottom). Afterwards your embedded config will be used and stored in `localStorage`.

Thank you for bringing this up, I’ll add it to the readme on the weekend.

**Comment by bonelifer** [comment]
Thanks for the quick reply.
