### ISSUE TITLE
some sites show wrong icon

### ISSUE THREAD

**Issue by cp66642** [michaelx/Launchbot#8]
https://keep.google.com/

**Comment by michaelx** [comment]
This is because it redirects to the Google sign in screen. You could define another favicon endpoint [here](https://github.com/michaelx/Launchbot/blob/393385eaa8a71755d2e9624ede3197dc1f2d1785/config.js#L54) (e.g. http://favicongrabber.com), but it won’t fix it, because you access the endpoint anonymously.

I think the best way to solve this is by proving an option to set a specific favicon per site.
